FROM registry.access.redhat.com/ubi10-minimal
ARG USER_HOME_DIR="/projects"

ENV HOME=${USER_HOME_DIR}
ENV BUILDAH_ISOLATION=chroot

USER 0

COPY --chown=0:0 useless-job.sh /

RUN microdnf --disableplugin=subscription-manager install -y procps-ng openssl git tar shadow-utils bash util-linux vim-minimal vim-enhanced ; \
    microdnf update -y ; \
    microdnf clean all ; \
    chmod +x /useless-job.sh ; \
    #
    # Add the user to /etc/passwd and /etc/group
    # Add the user with the UID that the SCC will enforce
    groupadd -g 375 user ; \
    useradd -u 375 -g 375 -d ${USER_HOME_DIR} -s /bin/bash user  ; \
    usermod -L user  ; \
    chmod 400 /etc/shadow  ; \
    chown -R 375:375 ${USER_HOME_DIR}
    

# The SCC that we are using will ensure that the user runs as UID 375 in its own user namespace on the host node.
USER 375
WORKDIR ${USER_HOME_DIR}
ENTRYPOINT ["/useless-job.sh"]
