apiVersion: v1                      
kind: Namespace                 
metadata:
  name: cekit-images
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cekit-images-image-puller-serviceaccounts
  namespace: cekit-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cekit-images-image-puller-users
  namespace: cekit-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: pipeline-user-namespaces
priority: null
allowPrivilegeEscalation: true
allowedCapabilities:
- SETUID
- SETGID
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1000
    max: 65534
runAsUser:
  type: MustRunAs
  uid: 1000
seLinuxContext:
  type: MustRunAs
  seLinuxOptions:
    type: container_engine_t
supplementalGroups:
  type: MustRunAs
  ranges:
  - min: 1000
    max: 65534
userNamespaceLevel: RequirePodLevel
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cekit-builder
  namespace: cekit-images
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-user-namespaces
  namespace: cekit-images
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - pipeline-user-namespaces
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-user-namespaces
  namespace: cekit-images
subjects:
  - kind: ServiceAccount
    name: cekit-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cekit-builder-user-namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cekit-image-builder
  namespace: cekit-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
- kind: ServiceAccount
  name: cekit-builder
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinned-image-sets
rules:
  - apiGroups:
      - machineconfiguration.openshift.io
    resources:
      - pinnedimagesets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-pinned-image-sets
subjects:
  - kind: ServiceAccount
    name: cekit-builder
    namespace: cekit-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pinned-image-sets
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-ist
  namespace: cekit-images
rules:
  - verbs:
      - get
      - watch
    apiGroups:
      - image.openshift.io
    resources:
      - imagestreamtags
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cekit-builder-ist
  namespace: cekit-images
subjects:
  - kind: ServiceAccount
    name: cekit-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cekit-builder-ist
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cekit-builder
  namespace: cekit-images
spec:
  source:
    git:
      uri: https://github.com/cgruver/opinionated-dev-spaces.git
      ref: main
    contextDir: "managed-images/cekit-builder-image"
  strategy:
    dockerStrategy:
      dockerfilePath: "./Containerfile"
  output:
    to:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/cekit-images/cekit-builder:latest
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cekit-build-all
  namespace: cekit-images
spec:
  params:
  - name: registry
    type: string
    description: Image registry that built images will be pushed to
  - name: registry-path
    type: string
    description: Path to the image within the registry
  - name: repository
    type: string
    description: The git repository to pull the image and module descriptors from.
  - name: revision
    type: string
    description: The repository branch to clone.
    default: "main"
  tasks:
  - name: base-images
    taskRef:
      name: cekit-class-builder
    params:
    - name: registry
      value: $(params.registry)
    - name: registry-path
      value: $(params.registry-path)
    - name: image-class
      value: developer
    - name: repository
      value: $(params.repository)
    - name: revision
      value: $(params.revision)
  - name: app-product-images
    runAfter:
    - base-images
    taskRef:
      name: cekit-class-builder
    params:
    - name: registry
      value: $(params.registry)
    - name: registry-path
      value: $(params.registry-path)
    - name: image-class
      value: app-product
    - name: repository
      value: $(params.repository)
    - name: revision
      value: $(params.revision)
  - name: utility-images
    runAfter:
    - base-images
    taskRef:
      name: cekit-class-builder
    params:
    - name: registry
      value: $(params.registry)
    - name: registry-path
      value: $(params.registry-path)
    - name: image-class
      value: utility
    - name: repository
      value: $(params.repository)
    - name: revision
      value: $(params.revision)
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cekit-build-class
  namespace: cekit-images
spec:
  params:
  - name: registry
    type: string
    description: Image registry that built images will be pushed to
  - name: registry-path
    type: string
    description: Path to the image within the registry
  - name: repository
    type: string
    description: The git repository to pull the image and module descriptors from.
  - name: revision
    type: string
    description: The repository branch to clone.
    default: "main"
  - name: class
    type: string
    description: The class of images to build
  tasks:
  - name: build-images
    taskRef:
      name: cekit-class-builder
    params:
    - name: registry
      value: $(params.registry)
    - name: registry-path
      value: $(params.registry-path)
    - name: image-class
      value: $(params.class)
    - name: repository
      value: $(params.repository)
    - name: revision
      value: $(params.revision)
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cekit-class-builder
  namespace: cekit-images
  annotations:
    io.kubernetes.cri-o.Devices: '/dev/fuse,/dev/net/tun'
spec:
  params:
  - name: registry
    type: string
    description: Image registry that built images will be pushed to
  - name: registry-path
    type: string
    description: Path to the image within the registry
  - name: image-class
    type: string
    description: The group of images to be built.  base, utility, app-product
  - name: repository
    type: string
    description: The git repository to pull the image and module descriptors from.
  - name: revision
    type: string
    description: The repository branch to clone.
    default: "main"
  stepTemplate:
    securityContext:
      capabilities:
        add:
          - SETGID
          - SETUID
        drop:
          - ALL
      runAsUser: 1000
      runAsNonRoot: true
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: true
      procMount: Unmasked
  steps:
  - name: clone
    image: image-registry.openshift-image-registry.svc:5000/cekit-images/cekit-builder:latest
    script: |
      git clone -b $(params.revision) --single-branch $(params.repository) /workspace/source
  - name: build
    image: image-registry.openshift-image-registry.svc:5000/cekit-images/cekit-builder:latest
    workingDir: "/workspace/source"
    env:
    - name: NODE_EXTRA_CA_CERTS
      value: /tekton-custom-certs/ca-bundle.crt
    script: |
      cd images/$(params.image-class)
      touch ist.list
      for image in $(ls *.yaml)
      do
        IMAGE_NAME=$(yq e ".name" ${image})
        IMAGE_TAG=$(yq e ".version" ${image})
        echo "${IMAGE_NAME}:${IMAGE_TAG}" >> ist.list
        IMAGE="$(params.registry)/$(params.registry-path)/${IMAGE_NAME}:${IMAGE_TAG}"
        cekit --descriptor ${image} build podman --build-flag --volume --build-flag ${NODE_EXTRA_CA_CERTS}:${NODE_EXTRA_CA_CERTS}:ro,Z --build-arg NODE_EXTRA_CA_CERTS=${NODE_EXTRA_CA_CERTS} --build-flag --manifest --build-flag ${IMAGE}
        podman manifest push ${IMAGE}
        podman manifest rm ${IMAGE}
       
      done
  - name: create-pinnedimageset
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    workingDir: "/workspace/source"
    script: |
      cd images/$(params.image-class)
      cat << EOF > pinned-images.yaml
      apiVersion: machineconfiguration.openshift.io/v1
      kind: PinnedImageSet
      metadata:
        name: cekit-builder-images-$(params.image-class)
        labels:
          machineconfiguration.openshift.io/role: master
      spec:
        pinnedImages:
      EOF

      for ist in $(cat ist.list)
      do
        IMAGE_SHA=$(oc get imagestreamtag ${ist} -o jsonpath='{.image.metadata.name}')
        IMAGE_NAME=$(echo ${ist} | cut -d":" -f1)
        IMAGE_REF="$(params.registry)/$(params.registry-path)/${IMAGE_NAME}@${IMAGE_SHA}"
        echo "  - name: ${IMAGE_REF}" >> pinned-images.yaml
      done
      oc apply -f pinned-images.yaml
      rm pinned-images.yaml
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cekit-image-builder
  namespace: cekit-images
  annotations:
    io.kubernetes.cri-o.Devices: '/dev/fuse,/dev/net/tun'
spec:
  params:
  - name: registry
    type: string
    description: Image registry that built images will be pushed to
  - name: registry-path
    type: string
    description: Path to the image within the registry
  - name: image-path
    type: string
    description: The relative path of the image.yaml to be built.
  - name: repository
    type: string
    description: The git repository to pull the image and module descriptors from.
  - name: revision
    type: string
    description: The repository branch to clone.
    default: "main"
  stepTemplate:
    securityContext:
      capabilities:
        add:
          - SETGID
          - SETUID
        drop:
          - ALL
      runAsUser: 1000
      runAsNonRoot: true
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: true
      procMount: Unmasked
  steps:
  - name: clone
    image: image-registry.openshift-image-registry.svc:5000/cekit-images/cekit-builder:latest
    script: |
      git clone -b $(params.revision) --single-branch $(params.repository) /workspace/source
  - name: build
    image: image-registry.openshift-image-registry.svc:5000/cekit-images/cekit-builder:latest
    workingDir: "/workspace/source"
    env:
    - name: NODE_EXTRA_CA_CERTS
      value: /tekton-custom-certs/ca-bundle.crt
    script: |
      image_def="images/$(params.image-path)"
      IMAGE_NAME=$(yq e ".name" ${image_def})
      IMAGE_TAG=$(yq e ".version" ${image_def})
      IMAGE="$(params.registry)/$(params.registry-path)/${IMAGE_NAME}:${IMAGE_TAG}"
      cekit --descriptor ${image_def} build podman --build-flag --volume --build-flag ${NODE_EXTRA_CA_CERTS}:${NODE_EXTRA_CA_CERTS}:ro,Z --build-arg NODE_EXTRA_CA_CERTS=${NODE_EXTRA_CA_CERTS} --build-flag --manifest --build-flag ${IMAGE}
      podman manifest push ${IMAGE}
      podman manifest rm ${IMAGE}
  - name: create-pinned-image-manifest
    image: image-registry.openshift-image-registry.svc:5000/cekit-images/cekit-builder:latest
    workingDir: "/workspace/source"
    script: |
      image_def="images/$(params.image-path)"
      IMAGE_NAME=$(yq e ".name" ${image_def})
      IMAGE_TAG=$(yq e ".version" ${image_def})
      IMAGE="$(params.registry)/$(params.registry-path)/${IMAGE_NAME}:${IMAGE_TAG}"
      IMAGE_SHA=$(podman manifest inspect ${IMAGE} | yq -p json -r '.manifests[0].digest')
      IMAGE_REF="$(params.registry)/$(params.registry-path)/${IMAGE_NAME}@${IMAGE_SHA}"
      cat << EOF > pin-image.yaml
      apiVersion: machineconfiguration.openshift.io/v1
      kind: PinnedImageSet
      metadata:
        name: cekit-builder-image-${IMAGE_NAME}-${IMAGE_TAG}
      spec:
        pinnedImages:
        - name: ${IMAGE_REF}
      EOF
  - name: apply-pinnedimageset
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    workingDir: "/workspace/source"
    script: |
      oc apply -f pin-image.yaml
      rm pin-image.yaml


