apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: test-cekit-
  namespace: cekit-images
spec:
  taskRef:
    name: cekit-image-builder
  params:
  - name: registry
    value: "image-registry.openshift-image-registry.svc:5000"
  - name: registry-path
    value: cekit-images
  - name: image-path
    value: app-product/cajun-navy.yaml
  - name: repository
    value: https://github.com/cgruver/cekit-image-library.git
  - name: revision
    value: main
  podTemplate:
    hostUsers: false
  serviceAccountName: cekit-builder