apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cekit-build-all
  namespace: cekit-build
spec:
  params:
  - name: registry
    type: string
    description: Image registry that built images will be pushed to
  - name: registry-path
    type: string
    description: Path to the image within the registry
  - name: repository
    type: string
    description: The git repository to pull the image and module descriptors from.
  - name: revision
    type: string
    description: The repository branch to clone.
    default: "main"
  tasks:
  - name: base-images
    taskRef:
      name: cekit-builder
    params:
    - name: registry
      value: $(params.registry)
    - name: registry-path
      value: $(params.registry-path)
    - name: image-class
      value: developer
    - name: repository
      value: $(params.repository)
    - name: revision
      value: $(params.revision)
  - name: app-product-images
    runAfter:
    - base-images
    taskRef:
      name: cekit-builder
    params:
    - name: registry
      value: $(params.registry)
    - name: registry-path
      value: $(params.registry-path)
    - name: image-class
      value: app-product
    - name: repository
      value: $(params.repository)
    - name: revision
      value: $(params.revision)
  - name: utility-images
    runAfter:
    - base-images
    taskRef:
      name: cekit-builder
    params:
    - name: registry
      value: $(params.registry)
    - name: registry-path
      value: $(params.registry-path)
    - name: image-class
      value: utility
    - name: repository
      value: $(params.repository)
    - name: revision
      value: $(params.revision)