FROM registry.access.redhat.com/ubi10-minimal

ENV HOME=/projects
ENV BUILDAH_ISOLATION=chroot

USER 0

COPY --chown=0:0 entrypoint.sh /

RUN microdnf --disableplugin=subscription-manager install -y procps-ng openssl git tar shadow-utils bash zsh podman buildah skopeo python3-pip python3-devel aardvark-dns fuse-overlayfs util-linux vim-minimal vim-enhanced sudo ; \
    microdnf update -y ; \
    microdnf clean all ; \
    pip3 install -U podman-compose ; \
    chmod +x /entrypoint.sh ; \
    ##
    ## Setup for root-less podman
    ##
    # Create the User's home directory
    mkdir -p ${HOME} ; \
    chown -R 1000:1000 ${HOME} ; \
    #
    # Add the user to /etc/passwd and /etc/group
    echo "user:x:1000:1000:devspaces user:${HOME}:/bin/bash" >> /etc/passwd ; \
    echo "user:x:1000:" >> /etc/group ; \
    #
    # Create entries in /etc/shadow
    #
    chmod 600 /etc/shadow ; \
    echo "user:*:0:0:99999:7:::" >> /etc/shadow ; \
    #
    # Add entries for uid and gid mappings for the user
    echo "user:1001:64535" >> /etc/subuid ; \
    echo "user:1001:64535" >> /etc/subgid ; \
    #
    # Enable podman to create uid and gid maps for the user
    setcap cap_setuid+ep /usr/bin/newuidmap ; \
    setcap cap_setgid+ep /usr/bin/newgidmap ; \
    #
    # Enable sudo
    #
    echo "user ALL=NOPASSWD: ALL" >> /etc/sudoers

# The SCC that we are using will ensure that the user runs as UID 1000 in its own user namespace on the host node.
USER 1000
WORKDIR ${HOME}
# Using catatonit ensures that our running container has a process reaper.  This avoids zombie processes in the container.
ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]
