apiVersion: v1                      
kind: Namespace                 
metadata:
  name: devspaces
---
apiVersion: org.eclipse.che/v2 
kind: CheCluster   
metadata:              
  name: devspaces  
  namespace: devspaces
spec:                         
  components:
    imagePuller:
      enable: true
      spec:
        daemonsetName: devworkspace-image-puller
        deploymentName: devworkspace-image-puller
        images: 'traefik-rhel9=registry.redhat.io/devspaces/traefik-rhel9@sha256:a94594615d9d52cb42a26b6ef816eeb49db5bb3e24a00724cbdb686363a70cd3;devworkspace-project-clone-rhel9=registry.redhat.io/devworkspace/devworkspace-project-clone-rhel9@sha256:c3c279ce6e0c85f983ec5ece1b9c9e5a7773dd25611f0c15fe2849ce0666deb6;che-code-insiders=quay.io/che-incubator/che-code:insiders;code-rhel9=registry.redhat.io/devspaces/code-rhel9@sha256:11a105b3192f7e1dc0368ae9b5b79b206798164d6a7071a5aecf2cf71c525ca7'
        nodeSelector: '{"node-role.kubernetes.io/devworkspace":""}'
    cheServer:      
      debug: false
      logLevel: INFO
    metrics:                
      enable: true
    pluginRegistry: {}
    devfileRegistry:
      disableInternalRegistry: true   
  containerRegistry: {}   
  devEnvironments:       
    startTimeoutSeconds: 300
    secondsOfRunBeforeIdling: -1
    maxNumberOfWorkspacesPerUser: 15
    maxNumberOfRunningWorkspacesPerUser: 5
    disableContainerBuildCapabilities: false
    disableContainerRunCapabilities: false
    defaultComponents:
    - name: dev-tools
      container:
        image: image-registry.openshift-image-registry.svc:5000/cekit-images/workspace-base:ubi10
        memoryLimit: 8Gi
        memoryRequest: 1Gi
        cpuLimit: "1"
        cpuRequest: 100m
        mountSources: true
    defaultEditor: che-incubator/che-code/latest
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    imagePullPolicy: IfNotPresent
    nodeSelector:  
        node-role.kubernetes.io/devworkspace: ""
    secondsOfInactivityBeforeIdling: 1800
    storage:
      pvcStrategy: per-workspace
  gitServices: {}
  networking: {}
