apiVersion: v1                      
kind: Namespace                 
metadata:
  name: devspaces
---           
apiVersion: org.eclipse.che/v2 
kind: CheCluster   
metadata:              
  name: devspaces  
  namespace: devspaces
spec:                         
  components:                  
    cheServer:      
      debug: false
      logLevel: INFO
    metrics:                
      enable: true
    pluginRegistry: {}
    devfileRegistry:
      disableInternalRegistry: true   
  containerRegistry: {}   
  devEnvironments:       
    startTimeoutSeconds: 300
    secondsOfRunBeforeIdling: -1
    maxNumberOfWorkspacesPerUser: 15
    maxNumberOfRunningWorkspacesPerUser: 5
    disableContainerBuildCapabilities: false
    disableContainerRunCapabilities: false
    defaultComponents:
    - name: dev-tools
      container:
        image: quay.io/cgruver0/che/dev-tools:latest
        memoryLimit: 6Gi
        memoryRequest: 1Gi
        cpuLimit: "1"
        cpuRequest: 100m
        mountSources: true
    defaultEditor: che-incubator/che-code/latest
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: 1800
    storage:
      pvcStrategy: per-workspace
      perWorkspaceStrategyPvcConfig:
        storageClass: qnap-iscsi
  gitServices: {}
  networking: {}