apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-global-settings-json
  namespace: devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /checode/remote/data/Machine
data:
  settings.json: |
    {
      "workbench.colorTheme": "Dark 2026",
      "workbench.preferredDarkColorTheme": "Winter is Coming (Dark Blue)",
      "workbench.preferredLightColorTheme": "Winter is Coming (Light)",
      "editor.wordWrap": "on",
      "files.autoSave": "off",
      "zoo-code.autoImportSettingsPath": "/globalconfig/zoo-code-settings.json",
      "chat.disableAIFeatures": true,
      "git.defaultCloneDirectory": "/projects/",
      "kilo-code.new.autocomplete.enableAutoTrigger": false,
      "kilo-code.new.autocomplete.enableChatAutocomplete": false,
      "kilo-code.new.autocomplete.enableSmartInlineTaskKeybinding": false,
      "kilo-code.new.browserAutomation.enabled": false,
      "kilo-code.new.browserAutomation.headless": false,
      "kilo-code.new.browserAutomation.useSystemChrome": false
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-global-extensions-json
  namespace: devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspaces-config
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /checode/remote/extensions
data:
  extensions.json: |
    {
      "recommendations": [
      "dbaeumer.vscode-eslint",
      "redhat.vscode-yaml",
      "ms-kubernetes-tools.vscode-kubernetes-tools",
      "mhutchie.git-graph",
      "eamodio.gitlens",
      "streetsidesoftware.code-spell-checker",
      "sst-dev.opencode",
      "kilocode.kilo-code",
      "cnshenj.vscode-task-manager"
      ]
    }