apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: basic-workspace
  annotations:
    controller.devfile.io/allow-import-from: "*"
spec:
  components:
  - name: dev-tools
    container:
      image: nexus.clg.lab:5002/dev-spaces/workspace-base:latest
      memoryLimit: 6Gi
      memoryRequest: 1Gi
      cpuLimit: "2"
      cpuRequest: 100m
      mountSources: true
      env:
      - name: VSCODE_DEFAULT_WORKSPACE
        value: "$(PROJECT_SOURCE)/vscode.code-workspace"
  - volume:
      size: 50Gi
    name: projects